name: yolo11n_aug_v1
model: yolo11n.pt
data: ../yolo_dataset_v1/data.yaml
imgsz: 640
epochs: 100
batch: 16
patience: 30
seed: 0
device: 0
project: runs
optimizer: auto
workers: 0
mosaic: 1.0
mixup: 0.15
copy_paste: 0.10
scale: 0.6
translate: 0.15
